[build]
  base = "frontend"          # Base directory for the build command
  publish = "dist" # Directory to publish
  command = "npm run build"  # Build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
